[build]
command = "npm run build"
publish = "out"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.7
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"

# [[plugins]] // TODO https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/issues/26
#   package = "netlify-plugin-submit-sitemap"

[build.processing]
  skip_processing = true # disables asset optimization which Next.js takes care of

[dev]
framework = "#custom"
command = "npm run dev"
port = 8080
targetPort = 3000
autoLaunch = true